### ISSUE TITLE
Cannot use with PHP8

### ISSUE THREAD

**Issue by robhowe** [neilime/ansi-escapes-to-html#27]
With PHP8 installed, running composer gives the error:
`    - neilime/ansi-escapes-to-html[v2.0.0, ..., v2.0.1] require php ^7.2 -> your php version (8.1.12) does not satisfy that requirement.
`
I believe this is easily fixed by changing line 30 in composer.json  from:
`    "php": "^7.2"`
to
`    "php": ">=7.2.0"`

Thank you!  Yours is the best/only package I can find to convert ANSI color codes to HTML!

**Comment by neilime** [comment]
Hi @robhowe 

PHP 8 is supported in release https://github.com/neilime/ansi-escapes-to-html/releases/tag/v3.0.0

**Comment by robhowe** [comment]
Works perfectly for me now.  Thanks!
